### ISSUE TITLE
Two questions about colorized output

### ISSUE THREAD

**Issue by telemachus** [jeffzi/llscheck#4]
(Thanks for the tool, by the way. It seems great and very helpful.)

1. At the moment, on systems that support colorized output terminal escapes for color are written into the output even if the output is redirected to a file. (E.g., `llscheck > check-later.txt`.) I think a good practice for command-line apps is to add a check to [`isatty`](https://linux.die.net/man/3/isatty) to prevent terminal escapes in files or logs. Would you consider a pull request to add a check with `isatty`? I would probably use [luaposix](https://luaposix.github.io/luaposix/modules/posix.unistd.html#isatty) or [luaterm](https://github.com/hoelzro/lua-term).
2. Would you consider a pull request to add an option (e.g., `--no-color`) to suppress the colorization of the output? (I'm color blind, and I find it much easier to read uncolorized text. Also, some people just prefer no color.)

**Comment by jeffzi** [comment]
Hey @telemachus,

Thanks for the suggestions and for using the tool.

1. **isatty Check**: I agree to add a check for `isatty`. Detecting `isatty` consistently can be challenging, I think we can leverage [luasystem](https://lunarmodules.github.io/luasystem/modules/system.html#isatty) (version >= 0.3.0) with a fallback to `luaposix` based on what is installed. These libraries should remain optional dependencies to avoid unnecessary bloat.

2. **--no-color Option**: Adding a `--no-color` option makes a lot of sense. Additionally, we should support the [NO_COLOR](https://no-color.org/) environment variable to accommodate users who prefer uncolorized output by default.

Given these points, the priority order for handling color output should be:
1. Check `isatty`.
2. Check `--no-color` option.
3. Check `NO_COLOR` environment variable.
4. If none of the above conditions are met, enable color output.

Pull requests are welcome!

**Comment by jeffzi** [comment]
Closed by #6 
Release v0.5.0 includes the changes 🚀
